name: db
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  csv: ^6.0.0
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.3
  http: ^1.6.0
  path_provider: ^2.1.5
  postgres: ^3.4.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
